FROM public.ecr.aws/lambda/nodejs@sha256:2c93ad724a87d51dd14b6e8056c148043f5279a13718793ec236ae1e5e724a35 AS deps

# Lambda workdir chuẩn
WORKDIR ${LAMBDA_TASK_ROOT}

COPY package*.json .

RUN npm ci

FROM public.ecr.aws/lambda/nodejs@sha256:2c93ad724a87d51dd14b6e8056c148043f5279a13718793ec236ae1e5e724a35 AS builder

WORKDIR ${LAMBDA_TASK_ROOT}

COPY --from=deps ${LAMBDA_TASK_ROOT}/node_modules ./node_modules

COPY . .

RUN npx prisma generate

RUN npm run build

RUN npm prune --omit=dev && npm cache clean --force

FROM public.ecr.aws/lambda/nodejs@sha256:2c93ad724a87d51dd14b6e8056c148043f5279a13718793ec236ae1e5e724a35 AS runner

WORKDIR ${LAMBDA_TASK_ROOT}

ENV NODE_ENV=production

COPY --from=builder ${LAMBDA_TASK_ROOT}/node_modules ./node_modules
COPY --from=builder ${LAMBDA_TASK_ROOT}/package.json .
COPY --from=builder ${LAMBDA_TASK_ROOT}/package-lock.json .
COPY --from=builder ${LAMBDA_TASK_ROOT}/dist ./dist

# Lambda handler
CMD ["dist/lambda/api.handler"]
