import 'package:frontend/core/infrastructure/constants/text_strings.dart';

final Map<String, String> viChatbot = {
  TTexts.chatbotName: 'Tori',
  TTexts.chatbotOnline: 'Trực tuyến',
  TTexts.chatbotWelcomeMsg:
      'Xin chào! Tôi là trợ lý AI của bạn. Hôm nay tôi có thể giúp gì cho việc quản lý kho hàng của bạn?',
  TTexts.chatbotErrorTitle: 'Lỗi trò chuyện',
  TTexts.chatbotErrorMsg:
      'Gửi tin nhắn thất bại. Vui lòng kiểm tra kết nối và thử lại.',
  TTexts.chatbotTyping: 'AI đang gõ...',
  TTexts.chatbotEmptyInputWarning: 'Vui lòng nhập tin nhắn.',
  TTexts.chatbotMockResponse: 'Đang tích hợp API. Bạn vừa nói:',
  TTexts.chatbotFallbackReply: "Xin lỗi, tôi không hiểu yêu cầu này.",
  TTexts.chatbotConnectionError: "Rất tiếc! Mất kết nối tới AI 😢",
  TTexts.chatbotResetTitle: "Làm mới cuộc trò chuyện",
  TTexts.chatbotResetMessage:
      "Bạn có chắc chắn muốn xóa toàn bộ tin nhắn không? Hành động này không thể hoàn tác.",
  TTexts.chatbotResetBtn: "Làm mới",
  TTexts.chatbotTransactionSuccess:
      "Giao dịch thành công! Dữ liệu kho đã được cập nhật.",
  TTexts.chatbotTransactionFailed:
      "Giao dịch thất bại. Yêu cầu có thể đã hết hạn.",
  TTexts.chatbotSuggestionTitle: 'Tôi có thể giúp gì cho bạn?',
  TTexts.chatbotSuggestionSub:
      'Chọn một gợi ý hoặc nhập yêu cầu của bạn bên dưới.',
  TTexts.chatbotPromptLowStock: 'Những mặt hàng nào sắp hết?',
  TTexts.chatbotPromptCheckInfo: 'Kiểm tra thông tin',
  TTexts.chatbotPromptImport: 'Tạo phiếu nhập',
  TTexts.chatbotPromptExport: 'Tạo phiếu xuất',
  TTexts.chatbotConfirmImport: 'Xác nhận Nhập kho',
  TTexts.chatbotConfirmExport: 'Xác nhận Xuất kho',
  TTexts.chatbotResolved: '(Đã giải quyết)',
  TTexts.chatbotActionCancelled: 'Đã hủy thao tác.',
  TTexts.chatbotOutOfStock: 'Hết hàng',
  TTexts.chatbotLowStockPrefix: 'Sắp hết:',
  TTexts.chatbotLeftPrefix: 'Còn lại:',
  TTexts.chatbotInStockPrefix: 'Tồn kho:',
  TTexts.chatbotLowStockAlert: 'Cảnh báo sắp hết:',
  TTexts.chatbotLowStockFoundPrefix: 'Tôi tìm thấy',
  TTexts.chatbotLowStockFoundSuffix:
      'sản phẩm đang cạn kiệt kho. Vui lòng lướt để xem các thẻ bên dưới:',
  TTexts.chatbotViewFullList: 'Xem danh sách đầy đủ ->',
  TTexts.chatbotNoImageTitle: 'Không có ảnh',
  TTexts.chatbotNoImageDesc: 'Ảnh sản phẩm không khả dụng',
  TTexts.chatbotMenuLowStock: 'Sản phẩm sắp hết',
  TTexts.chatbotMenuCreateImport: 'Tạo phiếu nhập',
  TTexts.chatbotMenuCreateExport: 'Tạo phiếu xuất',
  TTexts.chatbotQuickActionLowStock: 'Sắp hết',
  TTexts.chatbotQuickActionImport: 'Nhập kho',
  TTexts.chatbotQuickActionExport: 'Xuất kho',
  TTexts.chatbotSellingPrice: 'Giá bán',
  TTexts.chatbotImportPrice: 'Giá nhập',
  TTexts.chatbotViewDetail: 'Xem chi tiết kho',
  TTexts.chatbotTransactionConfirmedLabel: 'Đã tạo phiếu',
  TTexts.chatbotTransactionCancelledLabel: 'Đã hủy nháp',
  TTexts.chatbotTransactionCancelled: 'Đã hủy phiếu nháp thành công! ❌',
  TTexts.chatbotTransactionCancelFailed:
      'Không thể hủy phiếu nháp, vui lòng thử lại.',
  TTexts.chatbotSelected: 'Đã chọn',
  TTexts.chatbotCmdCheckInfo: 'Kiểm tra thông tin của',
  TTexts.chatbotCmdImport: 'Nhập',
  TTexts.chatbotCmdExport: 'Xuất',
  TTexts.chatbotInputHint: 'Yêu cầu nhập kho, kiểm tra tồn kho, xem nhật ký...',
  TTexts.chatbotPromptAuditLog: 'Lịch sử thao tác hôm nay',
  TTexts.chatbotPromptHelp: 'Hướng dẫn dùng Bot',
  TTexts.chatbotWelcomeDetailed:
      'Xin chào! Tôi là Tori, trợ lý AI của bạn. 🦉\n\nTôi có thể giúp bạn:\n📦 Tạo giao dịch Nhập/Xuất kho\n🔍 Kiểm tra tồn kho & cảnh báo\n🕒 Xem lịch sử thao tác hệ thống\n\nHôm nay tôi có thể giúp gì cho bạn?',
  TTexts.chatbotQuickActionInfo: 'Thông tin',
  TTexts.chatbotQuickActionHistory: 'Lịch sử',
  TTexts.chatbotQuickActionHelp: 'Trợ giúp',
  TTexts.chatbotPromptLowStockSub: 'Xem mặt hàng sắp hết',
  TTexts.chatbotPromptCheckInfoSub: 'Tìm theo tên sản phẩm',
  TTexts.chatbotPromptImportSub: 'Nhập tên & số lượng',
  TTexts.chatbotPromptExportSub: 'Nhập tên & số lượng',
  TTexts.chatbotPromptAuditLogSub: 'Xem thao tác gần đây (Beta)',
  TTexts.chatbotPromptHelpSub: 'Cách sử dụng Tori',
  TTexts.chatbotMessageTooLong: 'Tin nhắn quá dài (tối đa 100 ký tự).',
  TTexts.chatbotCoppiedSnackbar: "Sao chép vào bộ nhớ tạm thành công!"
};
