import 'package:frontend/core/infrastructure/constants/text_strings.dart';

final Map<String, String> viExport = {
  TTexts.exportExcelSystemName: 'STORIX',
  TTexts.exportExcelTitle: 'BÁO CÁO GIAO DỊCH HÀNG NGÀY',
  TTexts.exportExcelDate: 'Ngày:',
  TTexts.exportExcelTotalTx: 'Tổng Giao Dịch:',
  TTexts.exportExcelColNo: 'STT',
  TTexts.exportExcelColId: 'Mã Giao Dịch',
  TTexts.exportExcelColTime: 'Thời Gian',
  TTexts.exportExcelColType: 'Loại',
  TTexts.exportExcelColStatus: 'Trạng Thái',
  TTexts.exportExcelColItems: 'Tổng Sản Phẩm',
  TTexts.exportExcelColAmount: 'Tổng Tiền (\$)',
  TTexts.exportExcelGrandTotal: 'TỔNG CỘNG:',
  TTexts.exportPermissionChecking: 'Đang kiểm tra quyền...',
  TTexts.exportCreatingDoc: 'Đang tạo tài liệu...',
  TTexts.exportWritingSummary: 'Đang ghi tóm tắt...',
  TTexts.exportProcessingTx: 'Đang xử lý giao dịch...',
  TTexts.exportSavingFile: 'Đang lưu tệp...',
  TTexts.exportComplete: 'Xuất File Hoàn Tất!',
  TTexts.exportFileSaved: 'Tệp đã được lưu vào thư mục Downloads.',
  TTexts.exportOpenBtn: 'MỞ',
  TTexts.exportCannotOpen: 'Không thể mở tệp',
  TTexts.exportNoAppFound: 'Không tìm thấy ứng dụng để đọc file Excel (.xlsx).',
  TTexts.exportPreparing: 'Đang chuẩn bị xuất file...',
  TTexts.exportWritingTxInfo: 'Đang ghi thông tin giao dịch...',
  TTexts.exportReceiptTitle: 'BIÊN LAI GIAO DỊCH',
  TTexts.exportColProductName: 'Tên Sản Phẩm',
  TTexts.exportColBarcode: 'Mã Vạch',
  TTexts.exportColUnitPrice: 'Đơn Giá (\$)',
  TTexts.exportColQuantity: 'Số Lượng',
  TTexts.exportColTotal: 'Tổng (\$)',
  TTexts.exportProcessingItems: 'Đang xử lý sản phẩm...',
  TTexts.exportSuccessTitle: 'Xuất File Thành Công',
  TTexts.exportNoAppFoundDetail:
      'Không tìm thấy ứng dụng để đọc file Excel (.xlsx). Vui lòng cài đặt Microsoft Excel hoặc Google Sheets trên thiết bị của bạn.',
  TTexts.exportExcelStoreName: 'Tên Cửa Hàng:',
  TTexts.exportExcelAddress: 'Địa Chỉ:',
  TTexts.exportExcelExportedBy: 'Xuất Bởi:',
  TTexts.exportExcelExportTime: 'Thời Gian Xuất:',
};
