import 'package:frontend/core/infrastructure/constants/text_strings.dart';

final Map<String, String> viInventory = {
  TTexts.inventoryHub: 'Trung Tâm Kho Hàng',
  TTexts.manageProductsStock: 'Quản lý sản phẩm & tồn kho',
  TTexts.seeAllCategories: "Xem Tất Cả Danh Mục",

  // -- Inventory Module
  TTexts.details: 'Chi Tiết',
  TTexts.inboundOutbound7Days: 'Nhập vs Xuất (7 Ngày)',
  TTexts.inventoryTitle: 'Kho Hàng',
  TTexts.inventoryInsights: 'Phân Tích Kho Hàng',
  TTexts.manageData: 'Quản Lý Dữ Liệu',
  TTexts.productCatalog: 'Danh Mục Sản Phẩm',
  TTexts.chartTooltipIn: 'Nhập',
  TTexts.chartTooltipOut: 'Xuất',
  TTexts.initialQuantityLabel: "Số Lượng Ban Đầu",
  TTexts.initialQuantityHint: "0",
  TTexts.hideCategory: 'Ẩn Danh Mục',
  TTexts.hideCategoryTitle: 'Ẩn Danh Mục',
  TTexts.hideCategoryConfirm:
      'Bạn có chắc muốn ẩn danh mục mặc định này không? Nó sẽ không còn xuất hiện trong cửa hàng của bạn.',
  TTexts.hide: 'Ẩn',
  TTexts.hideCategorySuccessMessage: 'Ẩn danh mục thành công.',
  TTexts.addNewProductDesc: 'Thêm sản phẩm mới vào danh mục này.',

  // -- Inventory Header & Health
  TTexts.stockValue: 'Giá Trị Tồn Kho',
  TTexts.stockHealth: 'Tình Trạng Kho',
  TTexts.statusHealthy: 'Ổn Định',
  TTexts.statusLow: 'Thấp',
  TTexts.statusOut: 'Hết',

  // -- Inventory Distribution & Flow
  TTexts.topCategoriesByVolume: 'Danh Mục Hàng Đầu Theo Số Lượng',
  TTexts.stockFlow: 'Luồng Hàng',
  TTexts.flowIn: 'Nhập',
  TTexts.flowOut: 'Xuất',

  // -- Inventory Categories
  TTexts.items: 'sản phẩm',
  TTexts.more: 'Thêm',

  TTexts.totalActiveProducts: 'Tổng Sản Phẩm Hoạt Động',
  TTexts.totalStockValue: 'Tổng Giá Trị Kho',
  TTexts.inventoryHealth: 'Tình Trạng Kho',
  TTexts.topCategories: 'Danh Mục Hàng Đầu',
  TTexts.inventoryFlow: 'Luồng Kho',

  // -- Inventory Insight
  TTexts.insightsOverview: 'Tổng Quan Phân Tích',
  TTexts.actionRequired: 'Cần Hành Động',
  TTexts.goodCondition: 'Tình Trạng Tốt',
  TTexts.inventoryList: 'Kho Hàng',
  TTexts.tabAll: 'Tất Cả',
  TTexts.allItems: 'Tất Cả Sản Phẩm',
  TTexts.tabHealthy: 'Ổn Định',
  TTexts.tabLowStock: 'Tồn Kho Thấp',
  TTexts.tabOutStock: 'Hết Hàng',
  TTexts.sku: 'SKU',
  TTexts.inStock: 'Còn Hàng',
  TTexts.totalInventory: 'Tổng Kho',
  TTexts.clearFilters: 'Xóa Bộ Lọc',
  TTexts.emptyFilterMessage:
      "Hãy thử thay đổi bộ lọc hoặc danh mục để tìm nội dung bạn cần.",

  // -- Inventory Detail
  TTexts.inventoryDetails: 'Chi Tiết Kho',
  TTexts.quantityInStock: 'Số Lượng Trong Kho',
  TTexts.reorderThreshold: 'Gợi Ý Đặt Hàng',
  TTexts.importPrice: 'Giá Nhập',
  TTexts.adjustStock: 'Điều Chỉnh Kho',
  TTexts.totalInStock: 'Tổng Tồn Kho',
  TTexts.lowStockAlert: 'Cảnh Báo Tồn Kho Thấp',
  TTexts.noThreshold: 'Không giới hạn',
  TTexts.productSku: 'SKU Sản Phẩm',
  TTexts.productPrice: 'Giá Sản Phẩm',
  TTexts.totalValue: 'Tổng Giá Trị',
  TTexts.editItem: 'Chỉnh Sửa',
  TTexts.deleteItem: 'Xóa',
  TTexts.deleteConfirmation: 'Xác Nhận Xóa',
  TTexts.confirmDeleteText: 'Bạn có chắc muốn xóa sản phẩm này không?',
  TTexts.delete: 'Xóa',
  TTexts.barcodeType: 'Loại',
  TTexts.noLimit: 'Không giới hạn',
  TTexts.thresholdTitle: 'Ngưỡng',
  TTexts.totalStockTitle: 'Tổng Tồn Kho',
  TTexts.featureComingSoon: 'Tính năng này sẽ sớm ra mắt!',
  TTexts.itemDeletedSuccess: 'Đã Xóa',
  TTexts.itemDeletedMessage: 'Sản phẩm đã được xóa thành công!',
  TTexts.info: 'Thông Tin',
  TTexts.totalStockInTitle: 'Tổng Nhập Kho',
  TTexts.totalStockOutTitle: 'Tổng Xuất Kho',
  TTexts.importCost: 'Chi Phí Nhập',
  TTexts.salePrice: 'Giá Bán',
  TTexts.profitMargin: 'Biên Lợi Nhuận',
  TTexts.barcodeLabel: 'Mã Vạch',
  TTexts.noRelatedPackages: 'Không có gói nào khác cho sản phẩm này.',
  TTexts.unknownPackage: 'Gói Không Xác Định',
  TTexts.left: 'còn lại',
  TTexts.stockMovement: 'Biến Động Kho',
  TTexts.data: 'Dữ Liệu',
  TTexts.chart: 'Biểu Đồ',
  TTexts.stockIn: 'Nhập Kho',
  TTexts.stockOut: 'Xuất Kho',
  TTexts.inventoryStatus: 'Trạng Thái Kho',
  TTexts.relatedPackages: 'Gói Liên Quan',
  TTexts.inventoryHistory: 'Lịch Sử Kho',
  TTexts.latestInventoryCount: 'Kiểm Kê Gần Nhất',
  TTexts.restockFromSupplier: 'Nhập Hàng Từ Nhà Cung Cấp',
  TTexts.salesOrder: 'Đơn Bán Hàng #1023',
  TTexts.loadingProduct: 'Đang tải chi tiết sản phẩm...',
  TTexts.viewProductInfo: 'Xem Thông Tin Sản Phẩm',
  TTexts.productDataMissing: 'Thiếu dữ liệu sản phẩm',

  TTexts.noHistoryAvailable: 'Không có lịch sử cho sản phẩm này.',
  TTexts.importGoods: 'Nhập Hàng',
  TTexts.exportGoods: 'Xuất Hàng',
  TTexts.stockTake: 'Kiểm Kê',
  TTexts.stockAdjustmentOrCheck: 'Kiểm Kê / Điều Chỉnh',
  TTexts.currentQty: 'SL Hiện Tại',
  TTexts.errorProductOrPackageIdMissing: 'Thiếu ID sản phẩm hoặc ID gói.',
  TTexts.deleteProductImageTitle: "Xóa Ảnh Sản Phẩm",
  TTexts.deleteProductImageMessage:
      "Bạn có chắc muốn xóa ảnh hiện tại và để sản phẩm này không có ảnh?",

  // --- Transaction Bottom Sheet ở trang Detail ---
  TTexts.addToTransaction: 'Thêm Vào Giao Dịch',
  TTexts.enterQuantityToAdd: 'Nhập Số Lượng',
  TTexts.quantityToImport: 'Số lượng nhập',
  TTexts.importPriceLot: 'Giá Nhập (VND)',
  TTexts.confirmAndAdd: 'Xác Nhận & Thêm',

  // -- Product Catalog & Categories ---
  TTexts.categoryCatalog: 'Danh Mục Sản Phẩm',
  TTexts.searchCategories: 'Tìm kiếm danh mục...',
  TTexts.totalCategories: 'Tổng',
  TTexts.categoriesUnit: 'danh mục',
  TTexts.addNewCategory: 'Thêm Danh Mục Mới',
  TTexts.addNewCategorySub: 'Tạo nhóm phân loại mới cho kho hàng của bạn.',
  TTexts.categoryDescription: 'Mô Tả Danh Mục',
  TTexts.noCategoryDescription: 'Danh mục này chưa có mô tả',
  TTexts.emptyCategoryMessage:
      'Không tìm thấy danh mục phù hợp. Hãy thử từ khóa khác hoặc thêm danh mục mới.',
  TTexts.viewAllProducts: 'Tất Cả Sản Phẩm',
  TTexts.viewAllProductsSub: 'Xem và quản lý toàn bộ sản phẩm trong cửa hàng',
  TTexts.deleteCategoryTitle: 'Xóa Danh Mục',
  TTexts.deleteCategoryWarning:
      'Danh mục này chứa sản phẩm. Bạn có muốn chuyển tất cả sản phẩm sang "Chưa Phân Loại" và tiếp tục xóa không?',
  TTexts.deleteCategoryConfirmBtn: 'Xác Nhận Xóa',
  TTexts.deleteCategorySuccess: 'Xóa danh mục thành công.',
  TTexts.productDataRefreshing: 'Đang làm mới dữ liệu sản phẩm...',
  TTexts.packageUpdatedSuccess: 'Cập nhật gói thành công.',
  TTexts.packageCreatedSuccess: 'Tạo gói thành công.',
  TTexts.variantLabel: 'Tên Biến Thể',
  TTexts.variantHint: 'ví dụ: 330ml, Đỏ, Lớn...',
  TTexts.enterBarcodeHint: 'Nhập mã vạch và nhấn Enter hoặc Quét',
  TTexts.barcodeTooShort: 'Mã vạch phải có ít nhất 5 ký tự',
  TTexts.barcodeDuplicate: 'Mã vạch này đã tồn tại',
  TTexts.barcodeAdded: 'Đã thêm mã vạch thành công',
  TTexts.invalidPrice: 'Vui lòng nhập số hợp lệ',
  TTexts.barcodeDeletedSuccess: 'Xóa mã vạch thành công',
  TTexts.barcodeDeleted: 'Đã xóa mã vạch',

  // -- Category Detail
  TTexts.addNewProduct: 'Thêm Sản Phẩm Mới',
  TTexts.addNewProductSub: 'Thêm sản phẩm mới vào danh mục này.',
  TTexts.editCategory: 'Chỉnh Sửa Danh Mục',
  TTexts.deleteCategory: 'Xóa Danh Mục',
  TTexts.noProductsFound: 'Không Tìm Thấy Sản Phẩm',
  TTexts.noProductsAssigned:
      'Hiện tại chưa có sản phẩm nào trong danh mục này.',
  TTexts.deleteCategoryConfirm: 'Bạn có chắc muốn xóa danh mục này không?',
  TTexts.deleting: 'Đang xóa...',

  // -- Product Catalog Detail
  TTexts.brand: 'Thương Hiệu',
  TTexts.packagesOrVariants: 'Gói / Biến Thể',
  TTexts.add: 'Thêm',
  TTexts.noPackagesFound: 'Không Tìm Thấy Gói',
  TTexts.addPackageSubtitle:
      'Thêm gói (biến thể, đơn vị, mã vạch) cho sản phẩm này để quản lý kho.',
  TTexts.noBarcode: 'Không Có Mã Vạch',
  TTexts.editProduct: 'Chỉnh Sửa Sản Phẩm',
  TTexts.deleteProduct: 'Xóa Sản Phẩm',
  TTexts.addNewPackage: 'Thêm Gói Mới',
  TTexts.editPackage: 'Chỉnh Sửa Gói',
};
