import 'package:frontend/core/infrastructure/constants/text_strings.dart';

final Map<String, String> viInventory = {
  TTexts.inventoryHub: 'Trung tâm kho hàng',
  TTexts.manageProductsStock: 'Quản lý sản phẩm và tồn kho',
  TTexts.seeAllCategories: "Xem tất cả danh mục",

  // -- Inventory Module
  TTexts.details: 'Chi tiết',
  TTexts.inboundOutbound7Days: 'Nhập vs Xuất (7 ngày)',
  TTexts.inventoryTitle: 'Kho hàng',
  TTexts.inventoryInsights: 'Phân tích kho hàng',
  TTexts.manageData: 'Quản lý dữ liệu',
  TTexts.productCatalog: 'Danh mục sản phẩm',
  TTexts.chartTooltipIn: 'Nhập',
  TTexts.chartTooltipOut: 'Xuất',
  TTexts.initialQuantityLabel: "Số lượng ban đầu",
  TTexts.initialQuantityHint: "0",
  TTexts.hideCategory: 'Ẩn danh mục',
  TTexts.hideCategoryTitle: 'Ẩn danh mục',
  TTexts.hideCategoryConfirm:
      'Bạn có chắc muốn ẩn danh mục mặc định này không? Danh mục sẽ không còn hiển thị trong cửa hàng.',
  TTexts.hide: 'Ẩn',
  TTexts.hideCategorySuccessMessage: 'Ẩn danh mục thành công.',
  TTexts.addNewProductDesc: 'Thêm sản phẩm mới vào danh mục này.',

  // -- Inventory Header & Health
  TTexts.stockValue: 'Giá trị tồn kho',
  TTexts.stockHealth: 'Tình trạng kho',
  TTexts.statusHealthy: 'Ổn định',
  TTexts.statusLow: 'Sắp hết',
  TTexts.statusOut: 'Hết hàng',

  // -- Inventory Distribution & Flow
  TTexts.topCategoriesByVolume: 'Danh mục nổi bật theo số lượng',
  TTexts.stockFlow: 'Luồng kho',
  TTexts.flowIn: 'Nhập',
  TTexts.flowOut: 'Xuất',

  // -- Inventory Categories
  TTexts.items: 'sản phẩm',
  TTexts.more: 'Thêm',

  TTexts.totalActiveProducts: 'Tổng sản phẩm hoạt động',
  TTexts.totalStockValue: 'Tổng giá trị tồn kho',
  TTexts.inventoryHealth: 'Tình trạng kho',
  TTexts.topCategories: 'Danh mục nổi bật',
  TTexts.inventoryFlow: 'Luồng kho',

  // -- Inventory Insight
  TTexts.insightsOverview: 'Tổng quan',
  TTexts.actionRequired: 'Cần xử lý',
  TTexts.goodCondition: 'Ổn định',
  TTexts.inventoryList: 'Kho hàng',
  TTexts.tabAll: 'Tất cả',
  TTexts.allItems: 'Tất cả sản phẩm',
  TTexts.tabHealthy: 'Ổn định',
  TTexts.tabLowStock: 'Sắp hết',
  TTexts.tabOutStock: 'Hết hàng',
  TTexts.sku: 'Mã SKU',
  TTexts.inStock: 'Còn hàng',
  TTexts.totalInventory: 'Tổng tồn kho',
  TTexts.clearFilters: 'Xóa bộ lọc',
  TTexts.emptyFilterMessage:
      "Hãy thử thay đổi bộ lọc hoặc danh mục để tìm nội dung bạn cần.",

  // -- Inventory Detail
  TTexts.inventoryDetails: 'Chi tiết kho hàng',
  TTexts.quantityInStock: 'Số lượng tồn kho',
  TTexts.reorderThreshold: 'Ngưỡng nhập thêm',
  TTexts.importPrice: 'Giá nhập',
  TTexts.adjustStock: 'Điều chỉnh tồn kho',
  TTexts.totalInStock: 'Tổng tồn',
  TTexts.lowStockAlert: 'Cảnh báo sắp hết hàng',
  TTexts.noThreshold: 'Không giới hạn',
  TTexts.productSku: 'Mã sản phẩm',
  TTexts.productPrice: 'Giá sản phẩm',
  TTexts.totalValue: 'Tổng giá trị',
  TTexts.editItem: 'Chỉnh sửa sản phẩm',
  TTexts.deleteItem: 'Xóa sản phẩm',
  TTexts.deleteConfirmation: 'Xác nhận xóa',
  TTexts.confirmDeleteText: 'Bạn có chắc muốn xóa sản phẩm này không?',
  TTexts.delete: 'Xóa',
  TTexts.barcodeType: 'Loại',
  TTexts.noLimit: 'Không giới hạn',
  TTexts.thresholdTitle: 'Ngưỡng',
  TTexts.totalStockTitle: 'Tổng tồn kho',
  TTexts.featureComingSoon: 'Tính năng sắp ra mắt!',
  TTexts.itemDeletedSuccess: 'Đã xóa',
  TTexts.itemDeletedMessage: 'Sản phẩm đã được xóa thành công!',
  TTexts.info: 'Thông tin',
  TTexts.totalStockInTitle: 'Tổng nhập kho',
  TTexts.totalStockOutTitle: 'Tổng xuất kho',
  TTexts.importCost: 'Chi phí nhập',
  TTexts.salePrice: 'Giá bán',
  TTexts.profitMargin: 'Biên lợi nhuận',
  TTexts.barcodeLabel: 'Mã vạch',
  TTexts.noRelatedPackages: 'Không có gói sản phẩm liên quan.',
  TTexts.unknownPackage: 'Gói không xác định',
  TTexts.left: 'còn lại',
  TTexts.stockMovement: 'Biến động kho',
  TTexts.data: 'Dữ liệu',
  TTexts.chart: 'Biểu đồ',
  TTexts.stockIn: 'Nhập kho',
  TTexts.stockOut: 'Xuất kho',
  TTexts.inventoryStatus: 'Trạng thái kho',
  TTexts.relatedPackages: 'Gói liên quan',
  TTexts.inventoryHistory: 'Lịch sử kho',
  TTexts.latestInventoryCount: 'Kiểm kho gần nhất',
  TTexts.restockFromSupplier: 'Nhập từ nhà cung cấp',
  TTexts.salesOrder: 'Đơn bán #1023',
  TTexts.loadingProduct: 'Đang tải chi tiết sản phẩm...',
  TTexts.viewProductInfo: 'Xem thông tin sản phẩm',
  TTexts.productDataMissing: 'Thiếu dữ liệu sản phẩm',

  TTexts.noHistoryAvailable: 'Không có lịch sử cho sản phẩm này.',
  TTexts.importGoods: 'Nhập hàng',
  TTexts.exportGoods: 'Xuất hàng',
  TTexts.stockTake: 'Kiểm kho',
  TTexts.stockAdjustmentOrCheck: 'Kiểm kho / Điều chỉnh',
  TTexts.currentQty: 'SL hiện tại',
  TTexts.errorProductOrPackageIdMissing: 'Thiếu Product ID hoặc Package ID.',

  TTexts.deleteProductImageTitle: "Xóa ảnh sản phẩm",
  TTexts.deleteProductImageMessage:
      "Bạn có chắc muốn xóa ảnh hiện tại và để sản phẩm không có ảnh?",

  // --- Transaction Bottom Sheet ---
  TTexts.addToTransaction: 'Thêm vào giao dịch',
  TTexts.enterQuantityToAdd: 'Nhập số lượng',
  TTexts.quantityToImport: 'Số lượng nhập',
  TTexts.importPriceLot: 'Giá nhập',
  TTexts.confirmAndAdd: 'Xác nhận & Thêm',

  // -- Product Catalog & Categories ---
  TTexts.categoryCatalog: 'Danh mục sản phẩm',
  TTexts.searchCategories: 'Tìm kiếm danh mục...',
  TTexts.totalCategories: 'Tổng',
  TTexts.categoriesUnit: 'danh mục',
  TTexts.addNewCategory: 'Thêm danh mục mới',
  TTexts.addNewCategorySub: 'Tạo nhóm phân loại mới cho sản phẩm trong kho.',
  TTexts.categoryDescription: 'Mô tả danh mục',
  TTexts.noCategoryDescription: 'Danh mục này chưa có mô tả',
  TTexts.emptyCategoryMessage:
      'Không tìm thấy danh mục phù hợp. Hãy thử từ khóa khác hoặc tạo danh mục mới.',
  TTexts.viewAllProducts: 'Tất cả sản phẩm',
  TTexts.viewAllProductsSub: 'Xem và quản lý tất cả sản phẩm trong cửa hàng',
  TTexts.deleteCategoryTitle: 'Xóa danh mục',
  TTexts.deleteCategoryWarning:
      'Danh mục này chứa sản phẩm. Bạn có muốn chuyển toàn bộ sang "Chưa phân loại" rồi xóa không?',
  TTexts.deleteCategoryConfirmBtn: 'Xác nhận xóa',
  TTexts.deleteCategorySuccess: 'Xóa danh mục thành công.',
  TTexts.productDataRefreshing: 'Đang làm mới dữ liệu sản phẩm...',
  TTexts.packageUpdatedSuccess: 'Cập nhật gói thành công.',
  TTexts.packageCreatedSuccess: 'Tạo gói thành công.',

  TTexts.variantLabel: 'Tên biến thể',
  TTexts.variantHint: 'VD: 330ml, Đỏ, Lớn...',
  TTexts.enterBarcodeHint: 'Nhập barcode rồi Enter hoặc quét',
  TTexts.barcodeTooShort: 'Barcode phải có ít nhất 5 ký tự',
  TTexts.barcodeDuplicate: 'Barcode này đã tồn tại',
  TTexts.barcodeAdded: 'Đã thêm barcode',
  TTexts.invalidPrice: 'Vui lòng nhập số hợp lệ',
  TTexts.barcodeDeletedSuccess: 'Xóa barcode thành công',
  TTexts.barcodeDeleted: 'Đã xóa barcode',

  // -- Category Detail
  TTexts.addNewProduct: 'Thêm sản phẩm mới',
  TTexts.addNewProductSub: 'Thêm sản phẩm mới vào danh mục này.',
  TTexts.editCategory: 'Chỉnh sửa danh mục',
  TTexts.deleteCategory: 'Xóa danh mục',
  TTexts.noProductsFound: 'Không tìm thấy sản phẩm',
  TTexts.noProductsAssigned: 'Hiện chưa có sản phẩm nào trong danh mục này.',
  TTexts.deleteCategoryConfirm: 'Bạn có chắc muốn xóa danh mục này không?',
  TTexts.deleting: 'Đang xóa...',

  // -- Product Catalog Detail
  TTexts.brand: 'Thương hiệu',
  TTexts.packagesOrVariants: 'Gói / Biến thể',
  TTexts.add: 'Thêm',
  TTexts.noPackagesFound: 'Không tìm thấy gói',
  TTexts.addPackageSubtitle:
      'Thêm gói sản phẩm (biến thể, đơn vị, barcode) để quản lý tồn kho.',
  TTexts.noBarcode: 'Không có barcode',
  TTexts.editProduct: 'Chỉnh sửa sản phẩm',
  TTexts.deleteProduct: 'Xóa sản phẩm',
  TTexts.addNewPackage: 'Thêm gói mới',
  TTexts.editPackage: 'Chỉnh sửa gói',

  // -- Add Category
  TTexts.categoryNameLabel: 'Tên danh mục',
  TTexts.categoryNameHint: 'VD: Mỹ phẩm & Chăm sóc cá nhân',
  TTexts.categoryDescLabel: 'Mô tả (Tùy chọn)',
  TTexts.categoryDescHint: 'Mô tả ngắn về danh mục...',
  TTexts.saveCategory: 'Lưu danh mục',
  TTexts.categoryNameRequired: 'Tên danh mục là bắt buộc.',
  TTexts.categoryCreatedSuccessTitle: 'Thành công',
  TTexts.categoryCreatedSuccessMessage: 'Tạo danh mục thành công.',
  TTexts.categoryNameExists: 'Tên danh mục này đã tồn tại trong cửa hàng.',
  TTexts.saving: 'Đang lưu...',
  TTexts.savingCategory: 'Đang lưu danh mục...',

  // -- Edit Category
  TTexts.editCategoryTitle: 'Chỉnh sửa danh mục',
  TTexts.categoryUpdatedSuccessMessage: 'Cập nhật danh mục thành công.',
  TTexts.deleteCategorySuccessMessage: 'Đã xóa danh mục.',
  TTexts.categoryNotEmptyError:
      'Không thể xóa. Vui lòng xóa hoặc làm trống toàn bộ sản phẩm trong danh mục trước.',

  // -- Add Product
  TTexts.addNewProductTitle: 'Thêm sản phẩm mới',
  TTexts.editProductTitle: 'Chỉnh sửa thông tin sản phẩm',
  TTexts.productNameLabel: 'Tên sản phẩm',
  TTexts.productNameSubLabel: 'VD: Tên sản phẩm...',
  TTexts.selectCategory: 'Chọn danh mục',
  TTexts.initialPackageInfo: 'Gói ban đầu (Bắt buộc)',
  TTexts.unitLabel: 'Đơn vị (Cái, Hộp...)',
  TTexts.productCreatedSuccess: 'Tạo sản phẩm và gói ban đầu thành công.',
  TTexts.productUpdatedSuccess: 'Cập nhật sản phẩm thành công.',
  TTexts.step1: 'Bước 1',
  TTexts.step2: 'Bước 2',
  TTexts.baseInfo: 'Thông tin cơ bản',
  TTexts.packageInfo: 'Thông tin gói',
  TTexts.nextStep: 'Tiếp tục',
  TTexts.previousStep: 'Quay lại',
  TTexts.variantNameLabel: 'Tên biến thể',
  TTexts.variantNameHint: 'VD: Tuýp 150ml, Màu đỏ',
  TTexts.selectCategoryWarning: 'Vui lòng chọn danh mục trước.',
  TTexts.brandSub: 'VD: Thương hiệu',
  TTexts.tapToSelect: 'Nhấn để chọn...',
  TTexts.step1Title: 'Thông tin cơ bản',
  TTexts.step1Sub: 'Nhập các thông tin cơ bản của sản phẩm.',
  TTexts.step2Title: 'Gói ban đầu',
  TTexts.step2Sub: 'Tạo biến thể đầu tiên và thiết lập giá.',
  TTexts.productImage: 'Ảnh sản phẩm',
  TTexts.uploadImage: 'Tải ảnh lên',
  TTexts.takePhoto: 'Chụp ảnh',
  TTexts.chooseFromGallery: 'Chọn từ thư viện',
  TTexts.stepProductBaseInfo: 'Thông tin',
  TTexts.stepProductImage: 'Ảnh',
  TTexts.stepProductPackage: 'Giá bán',
  TTexts.productBaseTitle: 'Thông tin cơ bản',
  TTexts.productBaseSub: 'Bắt đầu với tên, thương hiệu và danh mục sản phẩm.',
  TTexts.productImageTitle: 'Ảnh sản phẩm',
  TTexts.productImageSub: 'Chụp hoặc tải ảnh sản phẩm.',
  TTexts.productPackageTitle: 'Gói & Giá bán',
  TTexts.productPackageSub: 'Thiết lập biến thể đầu tiên và giá bán.',
  TTexts.requirePhoto: 'Vui lòng chọn hoặc chụp ảnh sản phẩm trước.',
  TTexts.cameraPermissionDenied:
      'Cần cấp quyền camera để chụp ảnh. Hãy bật trong cài đặt.',
  TTexts.scanOrTypeBarcode: 'Quét hoặc nhập...',
  TTexts.zeroPointZero: "0.00",
  TTexts.selectUnit: 'Chọn đơn vị...',
  TTexts.discardChangesTitle: 'Hủy thay đổi?',
  TTexts.discardChangesMessage:
      'Bạn có chắc muốn quay lại? Mọi dữ liệu đã nhập sẽ bị mất.',
  TTexts.discard: 'Hủy bỏ',
  TTexts.keepEditing: 'Tiếp tục chỉnh sửa',
  TTexts.confirmNoImageTitle: 'Chưa chọn ảnh',
  TTexts.confirmNoImageMessage:
      'Bạn có chắc muốn tiếp tục mà không có ảnh sản phẩm?',
  TTexts.yesContinue: 'Tiếp tục',
  TTexts.addPhoto: 'Thêm ảnh',
  TTexts.cropImage: 'Chỉnh sửa ảnh',
  TTexts.reorderThresholdLabel: 'Cảnh báo tồn kho thấp',
  TTexts.reorderThresholdHint: 'VD: 5',

  TTexts.fieldRequired: 'Trường này là bắt buộc',
  TTexts.invalidNumber: 'Định dạng số không hợp lệ',
  TTexts.suggestedNames: 'Gợi ý:',
  TTexts.priceGreaterThanZero: 'Giá phải lớn hơn 0',

  // -- Edit Product
  TTexts.editProductImageTitle: 'Chỉnh sửa ảnh sản phẩm',
  TTexts.editProductImageSub: 'Cập nhật ảnh chính của sản phẩm.',
  TTexts.editPackageTitle: 'Chỉnh sửa gói',
  TTexts.editPackageSub: 'Cập nhật giá, barcode và ngưỡng tồn kho.',
  TTexts.addPackageTitle: 'Thêm gói mới',
  TTexts.addPackageSub: 'Tạo biến thể hoặc đơn vị mới cho sản phẩm.',
  TTexts.saveChanges: 'Lưu thay đổi',
  TTexts.saveImage: 'Lưu ảnh',
  TTexts.savePackage: 'Lưu gói',
  TTexts.deletePackage: 'Xóa gói',
  TTexts.addPackageBtn: 'Thêm gói',
  TTexts.imageUpdatedSuccess: 'Cập nhật ảnh sản phẩm thành công.',
  TTexts.deletingProduct: 'Đang xóa sản phẩm...',
  TTexts.productDeletedSuccess: 'Sản phẩm đã được chuyển vào thùng rác.',
  TTexts.deletingPackage: 'Đang xóa gói...',
  TTexts.packageDeletedSuccess: 'Gói đã được chuyển vào thùng rác.',
  TTexts.productNotEmptyError:
      'Không thể xóa sản phẩm. Vui lòng xóa hoặc làm trống toàn bộ gói trước.',
  TTexts.confirmMoveProductToTrash:
      'Bạn có chắc muốn chuyển sản phẩm vào thùng rác?',
  TTexts.confirmMovePackageToTrash:
      'Bạn có chắc muốn chuyển gói vào thùng rác?',
  TTexts.inventoryNotEmptyTitle: 'Kho vẫn còn hàng',
  TTexts.inventoryNotEmptyMessage:
      'Không thể xóa gói vì vẫn còn tồn kho. Vui lòng xử lý hết hàng trước.',
  TTexts.makeTransaction: 'Tạo giao dịch',
  TTexts.confirmDeletePackageMessage:
      'Bạn có chắc muốn xóa gói này? Gói sẽ được đánh dấu là không hoạt động.',
  TTexts.currentStockWithCount: 'Tồn kho hiện tại: @count',
  TTexts.importPriceLabel: 'Giá nhập',
  TTexts.sellingPriceLabel: 'Giá bán',
  TTexts.stockQuantityLabel: 'Tồn kho',
  TTexts.inventoryThreshold: 'Ngưỡng tồn kho',
  TTexts.sellingPrice: 'Giá bán',
  TTexts.unitLockedMessage: 'Không thể thay đổi đơn vị sau khi tạo.',
  TTexts.thresholdMustBeGreaterThanZero: 'Phải lớn hơn 0',
  TTexts.leaveEmptyForNoLimit: 'Để trống nếu không giới hạn',
  TTexts.displayNameSuffixLabel: 'Hậu tố biến thể (Tùy chọn)',
  TTexts.displayNameSuffixHint: 'VD: Đỏ, 500ml...',
  TTexts.displayNameLabel: 'Tên hiển thị',
  TTexts.displayNameHint: 'Sản phẩm + Đơn vị + Biến thể',
  TTexts.instructionTitle: 'Hướng dẫn nhập dữ liệu',
  TTexts.instructionBaseInfo:
      'Thông tin chung của sản phẩm (Tên, Thương hiệu, Danh mục). Áp dụng cho mọi biến thể.',
  TTexts.instructionImage: 'Ảnh vuông, rõ nét đại diện cho sản phẩm.',
  TTexts.instructionPackage:
      'Thông tin về sản phẩm thực tế bán ra. Chọn đơn vị và thiết lập biến thể.',
  TTexts.fillRequiredFields: 'Vui lòng nhập đầy đủ thông tin bắt buộc.',
  TTexts.confirmCreateTitle: 'Xác nhận tạo',
  TTexts.confirmCreateMessage: 'Bạn có chắc muốn tạo sản phẩm này?',
  TTexts.confirmUpdateTitle: 'Xác nhận cập nhật',
  TTexts.confirmUpdateMessage: 'Bạn có chắc muốn lưu thay đổi?',
  TTexts.confirmDeleteTitle: 'Xác nhận xóa',
  TTexts.confirmDeleteMessage:
      'Hành động này không thể hoàn tác. Bạn có chắc muốn xóa?',
  TTexts.confirmSkipPackageTitle: 'Bỏ qua tạo gói?',
  TTexts.confirmSkipPackageMessage:
      'Sản phẩm sẽ được tạo mà không có biến thể hoặc đơn vị.',
  TTexts.createOnlyProduct: 'Chỉ tạo sản phẩm',
  TTexts.createFullProduct: 'Tạo đầy đủ',
  TTexts.skipAndCreate: 'Bỏ qua & tạo sản phẩm',

  TTexts.customizeCatalog: 'Tùy chỉnh danh mục',
  TTexts.pinnedOnHome: 'Ghim trên trang chủ',
  TTexts.tapAndHoldToDrag: 'Nhấn giữ để kéo',
  TTexts.save: 'Lưu',
  TTexts.noDataAvailable: 'Không có dữ liệu',
  TTexts.noCategoriesFound: 'Không tìm thấy danh mục',
};
