import 'package:frontend/core/infrastructure/constants/text_strings.dart';

final Map<String, String> viSearch = {
  TTexts.searchEverything: 'Tìm kiếm mọi thứ...',
  TTexts.noResultsFound: 'Không tìm thấy sản phẩm',
  TTexts.didYouMean: "Ý bạn là",
  TTexts.transactionStatus: "Trạng Thái",
  TTexts.applyFilters: "Áp Dụng Bộ Lọc",
  TTexts.resetFilters: "Đặt Lại",
  TTexts.filterInbound: "Nhập Kho",
  TTexts.filterOutbound: "Xuất Kho",
  TTexts.filterAdjustment: "Điều Chỉnh",
  TTexts.filterCompleted: "Hoàn Thành",
  TTexts.filterPending: "Đang Chờ",
  TTexts.filterCancelled: "Đã Hủy",
  TTexts.searchTransactionHint: 'Tìm theo ID, mã vạch, ghi chú...',
  TTexts.noTransactionsFound: 'Không tìm thấy giao dịch',
  TTexts.dateRange: 'Khoảng Thời Gian',
  TTexts.selectDateRange: 'Chọn khoảng thời gian...',
  TTexts.createdByUser: 'Được Tạo Bởi Người Dùng',
  TTexts.enterUsernameOrId: 'Nhập tên người dùng hoặc ID...',
  TTexts.activeFilters: 'Bộ Lọc Đang Áp Dụng:',
  TTexts.userLabel: 'Người Dùng',
  TTexts.me: 'Tôi',
  TTexts.time: "Thời Gian",
  TTexts.allEmployees: "Tất Cả Nhân Viên",
  TTexts.loadingEmployees: "Đang tải danh sách nhân viên...",
  TTexts.filterNone: "Không",
  TTexts.supplier: "Nhà Cung Cấp",
  TTexts.customer: "Khách Hàng",
  TTexts.scrollDownToLoadMore: "Kéo xuống để xem thêm...",
};
