import 'package:frontend/core/infrastructure/constants/text_strings.dart';

final Map<String, String> viTransaction = {
  TTexts.createNewTransaction: "Tạo Giao Dịch Mới",
  TTexts.manageInventory: "Quản Lý Kho",
  TTexts.manageInventoryDesc:
      "Ghi nhận hàng nhập, hàng xuất hoặc điều chỉnh tồn kho hiện tại.",
  TTexts.inbound: "Nhập Kho",
  TTexts.outbound: "Xuất Kho",
  TTexts.stockAdjustment: "Điều Chỉnh Kho",
  TTexts.exit: "Thoát",
  TTexts.searchingProduct: "Đang tìm sản phẩm...",
  TTexts.unconfirmedBarcodeTitle: "Mã Vạch Chưa Xác Nhận",
  TTexts.unconfirmedBarcodeMessage:
      "Đã tìm thấy sản phẩm nhưng chưa được ánh xạ đúng. Vui lòng xác minh bên ngoài.",
  TTexts.barcodeNotFoundMessage: "Mã vạch không tồn tại trong hệ thống!",
  TTexts.errorProcessingBarcode: "Lỗi xử lý mã vạch",
  TTexts.tReason: "Lý Do",
  TTexts.updatePriceAndImport: "Cập Nhật & Nhập Kho",
  TTexts.importOnly: "Chỉ Nhập Kho",
  TTexts.confirmImportDesc:
      "Bạn có chắc muốn hoàn tất giao dịch nhập kho này không?",
  TTexts.sellingPriceChangeDetectedDesc:
      "Một số sản phẩm có giá bán khác với danh mục chính. Bạn có muốn cập nhật giá mặc định cho các giao dịch sau không?",
  TTexts.updatePriceAndExport: "Cập Nhật & Xuất Kho",
  TTexts.exportOnly: "Chỉ Xuất Kho",
  TTexts.confirmExportDesc:
      "Bạn có chắc muốn hoàn tất giao dịch xuất kho này không?",
  TTexts.significantChangeDetected: "Phát Hiện Thay Đổi Lớn",
  TTexts.highQtyFluctuationDesc:
      "Các sản phẩm sau có biến động số lượng lớn (>= 10 đơn vị):",
  TTexts.priceFluctuationDesc: "Các sản phẩm sau có thay đổi về giá.",
  TTexts.andMore: "và nhiều hơn nữa...",

  // -- Inbound
  TTexts.inboundTransaction: "Giao Dịch Nhập Kho",
  TTexts.emptyInboundCartTitle: "Chưa có sản phẩm nào",
  TTexts.emptyInboundCartSub:
      "Quét mã vạch hoặc nhấn thanh tìm kiếm để thêm sản phẩm vào giao dịch này.",
  TTexts.completeImport: "Hoàn Tất Nhập Kho",
  TTexts.totalFunds: "Tổng tiền",
  TTexts.searchProductToAdd: "Tìm sản phẩm để thêm...",
  TTexts.emptyTransactionTitle: "Chưa có sản phẩm nào",
  TTexts.emptyTransactionSubtitle:
      "Quét mã vạch hoặc nhấn thanh tìm kiếm để thêm sản phẩm vào giao dịch này.",
  TTexts.transactionCompletedTitle: "Hoàn Tất Giao Dịch!",
  TTexts.transactionCompletedSubtitle:
      "Giao dịch của bạn đã được xử lý và lưu thành công.",
  TTexts.backToHome: "Quay Về Trang Chủ",
  TTexts.scanProductBarcode: "Quét Mã Vạch Sản Phẩm",
  TTexts.confirmImportTitle: "Xác Nhận Nhập Kho",
  TTexts.confirmImportDescription:
      "Bạn có chắc muốn hoàn tất giao dịch nhập kho này không? Hành động này sẽ thêm hàng vào kho.",
  TTexts.proceedImport: "Xác Nhận & Nhập Kho",

  // -- Outbound
  TTexts.outboundTransactionTitle: 'Giao Dịch Xuất Kho',
  TTexts.searchDot: 'Tìm kiếm ...',
  TTexts.completeExport: 'Hoàn Tất Xuất Kho',
  TTexts.stocksLabel: 'Tồn kho:',
  TTexts.outOfStockAlert: 'Không đủ tồn kho!',
  TTexts.outOfStockTitle: "Hết Hàng!",
  TTexts.outOfStockDesc:
      "Một số sản phẩm trong giỏ hàng không còn đủ số lượng do thay đổi tồn kho gần đây. Chúng đã được cập nhật hoặc xóa khỏi giỏ.",
  TTexts.actualStock: "Tồn kho thực tế",
  TTexts.autoRemovedFromCart: "Tự động xóa khỏi giỏ hàng",
  TTexts.updatedListLabel: "Danh sách đã cập nhật:",
  TTexts.clearStock: "Xóa Tồn Kho",
  TTexts.clearAllStock: "Xóa Toàn Bộ Tồn Kho",
  TTexts.productHasRemainingStock:
      "Sản phẩm này vẫn còn tồn kho trong các gói hàng. Bạn cần xóa tồn kho trước khi xóa sản phẩm.",
  TTexts.autoGeneratedClearanceNote:
      "Giao dịch tự động tạo để xóa tồn kho trước khi xóa sản phẩm.",

  // --- Transaction Item Add ---
  TTexts.loadingAddingToCart: "Đang thêm vào giao dịch...",
  TTexts.productNameUnknown: "Sản Phẩm Không Xác Định",
  TTexts.labelNoBarcode: "N/A",
  TTexts.labelStock: "Tồn Kho",
  TTexts.labelImportPrice: "Giá Nhập (\$)",
  TTexts.labelQuantity: "Số Lượng",
  TTexts.labelTicket: "Phiếu",
  TTexts.errorNoPackageId: "Không tìm thấy hoặc ID gói không hợp lệ",
  TTexts.item: "Sản phẩm",
  TTexts.subtotal: "Tạm tính",
  TTexts.removeItem: "Xóa Sản Phẩm",
  TTexts.confirmRemoveItemTransaction:
      "Bạn có chắc muốn xóa sản phẩm này khỏi giao dịch không?",
  TTexts.remove: "Xóa",
  TTexts.creatingImportTicket: "Đang tạo phiếu nhập...",
  TTexts.manualImport: "Nhập Kho Thủ Công",
  TTexts.importTicketCreated: "Đã tạo phiếu nhập thành công!",
  TTexts.errorCreatingImportTicket: "Tạo phiếu nhập thất bại.",
  TTexts.uncategorized: "Chưa Phân Loại",
  TTexts.noBrand: "Không Có Thương Hiệu",
  TTexts.inactive: "Không Hoạt Động",
  TTexts.product: "Sản Phẩm",
  TTexts.recentlyAddedSuggested: "Mới Thêm / Đề Xuất",
  TTexts.checkoutDetails: 'Chi Tiết Thanh Toán',
  TTexts.transactionReason: 'Lý Do Giao Dịch',
  TTexts.selectReason: 'Chọn lý do',
  TTexts.transactionNote: 'Ghi Chú (Tùy chọn)',
  TTexts.noteHint: 'Nhập thêm chi tiết...',
  TTexts.priceChangeDetected: 'Phát Hiện Thay Đổi Giá',
  TTexts.priceChangeMessage:
      'Bạn đã thay đổi giá của một số sản phẩm trong giao dịch này. Bạn có muốn cập nhật vĩnh viễn giá mặc định trong danh mục không?',
  TTexts.updatePricesAndCreate: 'Cập Nhật Giá & Hoàn Tất',
  TTexts.justCreateTransaction: 'Không, Chỉ Hoàn Tất Giao Dịch',
  TTexts.transactionSuccessTitle: 'Giao dịch thành công!!!',
  TTexts.transactionSuccessSub:
      'Giao dịch của bạn đã hoàn tất.\nVui lòng kiểm tra tồn kho!',
  TTexts.transactionNumber: 'Mã Giao Dịch',
  TTexts.transactionDate: 'Ngày Giao Dịch',
  TTexts.transactionType: 'Loại Giao Dịch',
  TTexts.totalItemsTransaction: 'Tổng Sản Phẩm',
  TTexts.checkDetails: 'Xem Chi Tiết',
  TTexts.transactionDetails: 'Chi Tiết Giao Dịch',
  TTexts.selectExportType: "Chọn Loại Xuất:",
  TTexts.quantityGreaterThanZero: "Số lượng phải lớn hơn 0.",
  TTexts.unitPriceLabel: "Đơn Giá",
  TTexts.deleteSearchTitle: "Xóa Lịch Sử Tìm Kiếm",
  TTexts.deleteSearchMessage:
      "Bạn có chắc muốn xóa từ khóa tìm kiếm này không?",

  // Specific Reasons
  TTexts.reasonRetailSale: 'Bán Lẻ',
  TTexts.reasonWholesale: 'Bán Sỉ',
  TTexts.reasonDamaged: 'Hư Hỏng / Hết Hạn',
  TTexts.reasonInternalTransfer: 'Chuyển Nội Bộ',
  TTexts.reasonReturn: 'Trả Về Nhà Cung Cấp',
  TTexts.reasonOther: 'Khác',
  TTexts.reasonIncome: 'Thu Nhập (+)',
  TTexts.reasonNeutral: 'Không Doanh Thu (0)',
  TTexts.reasonExpense: 'Chi Phí / Thất Thoát (-)',

  TTexts.selectBatchFIFO: 'Chọn lô hàng',
  TTexts.batchRemaining: 'còn lại',
  TTexts.expiresOn: 'HSD',
  TTexts.batchExceedsStock: 'Số lượng vượt quá tồn kho của lô đã chọn!',
  TTexts.quantityToExport: 'Số lượng xuất',
  TTexts.importPriceLot: 'Giá Nhập',
  TTexts.sellingPriceLot: 'Giá Bán',
  TTexts.quantityToImport: 'Số lượng nhập',
  TTexts.importedOn: "Ngày nhập",
  TTexts.outOfStockBatch: "Hết hàng",
  TTexts.confirmExportTitle: "Xác Nhận Xuất Kho",
  TTexts.confirmExportDescription:
      "Bạn có chắc muốn hoàn tất giao dịch xuất kho này không? Hành động này sẽ cập nhật tồn kho.",
  TTexts.processingExport: "Đang xử lý xuất kho...",
  TTexts.exportSuccessMessage: "Giao dịch xuất kho hoàn tất thành công!",
  TTexts.noteLabel: "Ghi Chú",
  TTexts.emptyCartWarning:
      "Giỏ hàng đang trống. Vui lòng thêm sản phẩm trước khi xuất kho.",
  TTexts.priceChangeDetectedTitle: "Phát Hiện Thay Đổi Giá",
  TTexts.priceChangeDetectedDesc: "Các sản phẩm sau đã thay đổi giá bán:",
  TTexts.proceedExport: "Xác Nhận & Xuất Kho",
  TTexts.reasonForExport: "Lý Do Xuất Kho",
  TTexts.total: "Tổng",
  TTexts.totalQuantity: "Tổng Số Lượng",
  TTexts.specifyBatchQuantity:
      "Vui lòng chỉ định số lượng từ các lô hàng trên.",
  TTexts.outboundTransaction: "Giao Dịch Xuất Kho",
  TTexts.loadingCreatingTransaction: "Đang tạo giao dịch...",
  TTexts.creatingExportTicket: "Đang tạo phiếu xuất...",
  TTexts.exportTicketCreated: "Đã tạo phiếu xuất thành công!",

  // -- Stock Adjustment
  TTexts.confirmAdjustmentTitle: "Bắt Đầu Kiểm Kê?",
  TTexts.confirmAdjustmentDesc:
      "Bạn có chắc muốn bắt đầu phiên kiểm kê mới không? Điều này sẽ cho phép cập nhật số lượng tồn kho thực tế.",
  TTexts.proceedAdjustment: "Bắt Đầu Kiểm Kê",
  TTexts.listItems: "Danh sách sản phẩm",
  TTexts.system: "Hệ Thống",
  TTexts.actual: "Thực Tế",
  TTexts.spread: "Chênh Lệch",
  TTexts.status: "Trạng Thái",
  TTexts.checked: "Đã Kiểm",
  TTexts.unchecked: "Chưa Kiểm",
  TTexts.checkedItems: "Sản phẩm đã kiểm",
  TTexts.saveAll: "Lưu tất cả",
  TTexts.updateActualQty: "Cập Nhật Số Lượng Thực Tế",
  TTexts.mismatched: "Không Khớp",
  TTexts.reason: "Lý Do",
  TTexts.damage: "Hư Hỏng",
  TTexts.expired: "Hết Hạn",
  TTexts.loss: "Thất Thoát",
  TTexts.itemFound: "Đã Tìm Thấy Sản Phẩm",
  TTexts.inputError: "Lỗi nhập liệu",
  TTexts.additionalNote: "Ghi Chú Bổ Sung",
  TTexts.stockOutput: "XUẤT KHO:",
  TTexts.checkComplete: "Kiểm kê hoàn tất",
  TTexts.mismatchedReasonLabel: "Lý do chênh lệch (Hoặc ghi chú nếu có):",
  TTexts.productInformation: "Thông Tin Sản Phẩm",
  TTexts.stockCount: "Số Lượng Tồn:",
  TTexts.otherReason: "Lý Do Khác",
  TTexts.notEnoughStockWarning:
      "Bạn không thể đặt số lượng thực tế thấp hơn tồn kho hiện tại.",
  TTexts.quantityToAdjust: "Số Lượng Điều Chỉnh:",
  TTexts.automatedNote: "Ghi Chú Tự Động:",
  TTexts.currentStock: "Tồn Kho Hiện Tại",
  TTexts.barcode: "Mã Vạch",
  TTexts.checkAll: "Đánh Dấu Tất Cả",
  TTexts.uncheckAll: "Bỏ Đánh Dấu Tất Cả",
  TTexts.confirmCheckAllTitle: "Đánh Dấu Tất Cả Sản Phẩm?",
  TTexts.confirmCheckAllDesc:
      "Tất cả sản phẩm chưa kiểm sẽ được đánh dấu là đã kiểm với số lượng hệ thống (Chênh lệch: 0). Bạn có muốn tiếp tục không?",
  TTexts.confirmUncheckAllTitle: "Bỏ Đánh Dấu Tất Cả?",
  TTexts.confirmUncheckAllDesc:
      "Hành động này sẽ đặt lại tất cả sản phẩm về trạng thái chưa kiểm và xóa toàn bộ số lượng thực tế cùng ghi chú đã nhập. Tiếp tục?",
  TTexts.incompleteSaveTitle: "Kiểm Kê Chưa Hoàn Tất!",
  TTexts.incompleteSaveDesc:
      "Bạn chưa kiểm kê toàn bộ sản phẩm trong kho. Các sản phẩm chưa kiểm sẽ KHÔNG được cập nhật. Bạn có chắc muốn lưu ngay bây giờ không?",
  TTexts.confirmSaveTitle: "Lưu Điều Chỉnh Kho?",
  TTexts.confirmSaveDesc:
      "Hành động này sẽ cập nhật tồn kho và tạo bản ghi giao dịch điều chỉnh. Tiếp tục?",
  TTexts.combinedNotesTitle: "Tóm Tắt Ghi Chú Điều Chỉnh:",
  TTexts.errorLoadingData: "Lỗi tải dữ liệu. Vui lòng thử lại.",
  TTexts.verifyingData: "Đang xác minh dữ liệu tồn kho hiện tại...",
  TTexts.syncDataWarningTitle: "Dữ Liệu Tồn Kho Đã Thay Đổi!",
  TTexts.syncDataWarningDesc:
      "Một số sản phẩm đã bị thay đổi bởi tiến trình khác trong lúc bạn kiểm kê. Chúng tôi đã cập nhật Số Lượng Hệ Thống. Vui lòng kiểm tra lại các sản phẩm được đánh dấu.",
  TTexts.unsavedChangesTitle: "Hủy Thay Đổi?",
  TTexts.unsavedChangesDesc:
      "Bạn vẫn còn sản phẩm chưa kiểm. Nếu thoát bây giờ, tiến trình kiểm kê sẽ bị mất. Bạn có muốn thoát không?",
  TTexts.exitAnyway: "Vẫn Thoát",
  TTexts.inventoryUpdatedSuccess: "Đã cập nhật kho thành công.",
  TTexts.noReasonNeededWarning:
      "Bạn không cần chọn lý do khi không có chênh lệch.",
  TTexts.defaultAdjustmentNote: "Điều Chỉnh Kho (Không có chênh lệch/ghi chú)",
  TTexts.itemFoundText: "Đã tìm thấy",
  TTexts.defaultUnit: "Đơn Vị",
  TTexts.specificNoteHint: "Nhập ghi chú cụ thể (ví dụ: Hỏng 1 thùng bởi John)",
  TTexts.noItemsFound: "Không tìm thấy sản phẩm",
  TTexts.noItemsFoundDesc:
      "Chúng tôi không tìm thấy sản phẩm phù hợp với tìm kiếm của bạn. Vui lòng thử từ khóa khác hoặc quét lại.",
  TTexts.discardTransactionTitle: "Hủy Giao Dịch?",
  TTexts.discardTransactionDesc:
      "Bạn đang có sản phẩm trong phiếu. Nếu thoát bây giờ, giao dịch này sẽ bị mất. Bạn có muốn thoát không?",
  TTexts.noDifferencesFound:
      "Không tìm thấy chênh lệch nào. Vui lòng chỉnh sửa ít nhất một sản phẩm.",
  TTexts.adjustmentCompletedTitle: "Hoàn Tất Kiểm Kê",
  TTexts.adjustmentSuccessSub:
      "Điều chỉnh kho của bạn đã được xử lý thành công.",
  TTexts.adjustmentId: "Mã Điều Chỉnh",
  TTexts.checkItemsStats: "Kiểm Kê / Thống Kê Kho",

  TTexts.totalDifference: "Tổng Chênh Lệch",

  // -- Transaction Summary
  TTexts.qty: "SL",
  TTexts.modifiedProducts: "Sản Phẩm Đã Điều Chỉnh",
  TTexts.adjustmentSummaryBrief:
      "Đây là tóm tắt ngắn gọn của điều chỉnh kho. Để xem danh sách chi tiết các sản phẩm đã điều chỉnh, vui lòng kiểm tra Lịch Sử Giao Dịch.",
};
