import 'package:frontend/core/infrastructure/constants/text_strings.dart';

final Map<String, String> enExport = {
  TTexts.exportExcelSystemName: 'STORIX',
  TTexts.exportExcelTitle: 'DAILY TRANSACTION REPORT',
  TTexts.exportExcelDate: 'Date:',
  TTexts.exportExcelTotalTx: 'Total Transactions:',
  TTexts.exportExcelColNo: 'No.',
  TTexts.exportExcelColId: 'Transaction ID',
  TTexts.exportExcelColTime: 'Time',
  TTexts.exportExcelColType: 'Type',
  TTexts.exportExcelColStatus: 'Status',
  TTexts.exportExcelColItems: 'Total Items',
  TTexts.exportExcelColAmount: 'Total Amount (\$)',
  TTexts.exportExcelGrandTotal: 'GRAND TOTAL:',
  TTexts.exportPermissionChecking: 'Checking permissions...',
  TTexts.exportCreatingDoc: 'Creating document...',
  TTexts.exportWritingSummary: 'Writing summary...',
  TTexts.exportProcessingTx: 'Processing transactions...',
  TTexts.exportSavingFile: 'Saving file...',
  TTexts.exportComplete: 'Export Complete!',
  TTexts.exportFileSaved: 'File saved to Downloads folder.',
  TTexts.exportOpenBtn: 'OPEN',
  TTexts.exportCannotOpen: 'Cannot open file',
  TTexts.exportNoAppFound: 'No app found to read Excel (.xlsx) files.',
  TTexts.exportPreparing: 'Preparing to export...',
  TTexts.exportWritingTxInfo: 'Writing transaction info...',
  TTexts.exportReceiptTitle: 'TRANSACTION RECEIPT',
  TTexts.exportColProductName: 'Product Name',
  TTexts.exportColBarcode: 'Barcode',
  TTexts.exportColUnitPrice: 'Unit Price (\$)',
  TTexts.exportColQuantity: 'Quantity',
  TTexts.exportColTotal: 'Total (\$)',
  TTexts.exportProcessingItems: 'Processing items...',
  TTexts.exportSuccessTitle: 'Export Successful',
  TTexts.exportNoAppFoundDetail:
      'No app found to read Excel (.xlsx) files. Please install Microsoft Excel or Google Sheets on your device.',
  TTexts.exportExcelStoreName: 'Store Name:',
  TTexts.exportExcelAddress: 'Address:',
  TTexts.exportExcelExportedBy: 'Exported By:',
  TTexts.exportExcelExportTime: 'Export Time:',
};
