import 'package:frontend/core/infrastructure/constants/text_strings.dart';

final Map<String, String> enSearch = {
  TTexts.searchEverything: 'Search everything...',
  TTexts.noResultsFound: 'No products found',
  TTexts.didYouMean: "Did you mean",
  TTexts.transactionStatus: "Status",
  TTexts.applyFilters: "Apply Filters",
  TTexts.resetFilters: "Reset",
  TTexts.filterInbound: "Inbound",
  TTexts.filterOutbound: "Outbound",
  TTexts.filterAdjustment: "Adjustment",
  TTexts.filterCompleted: "Completed",
  TTexts.filterPending: "Pending",
  TTexts.filterCancelled: "Cancelled",
  TTexts.searchTransactionHint: 'Search by ID, barcode, note...',
  TTexts.noTransactionsFound: 'No transactions found',
  TTexts.dateRange: 'Date Range',
  TTexts.selectDateRange: 'Select a date range...',
  TTexts.createdByUser: 'Created By User',
  TTexts.enterUsernameOrId: 'Enter username or ID...',
  TTexts.activeFilters: 'Active Filters:',
  TTexts.userLabel: 'User',
  TTexts.me: 'Me',
  TTexts.time: "Time",
  TTexts.allEmployees: "All employees",
  TTexts.loadingEmployees: "Loading employees...",
  TTexts.filterNone: "None",
  TTexts.supplier: "Supplier",
  TTexts.customer: "Customer",
};
