import 'package:flutter/material.dart';
import 'package:frontend/core/infrastructure/constants/text_strings.dart';
import 'package:frontend/core/infrastructure/models/transaction_detail_model.dart';
import 'package:frontend/core/infrastructure/models/transaction_model.dart';
import 'package:frontend/core/infrastructure/models/product_package_model.dart';
import 'package:frontend/core/infrastructure/models/inventory_model.dart';
import 'package:frontend/core/infrastructure/utils/error_handler_utils.dart';
import 'package:frontend/core/infrastructure/utils/full_screen_loader_utils.dart';
import 'package:frontend/core/ui/layouts/t_barcode_scanner_layout.dart';
import 'package:frontend/core/ui/widgets/t_snackbars_widget.dart';
import 'package:frontend/core/ui/widgets/t_custom_dialog_widget.dart';
import 'package:frontend/features/home/controllers/home_controller.dart';
import 'package:frontend/features/report/controllers/report_controller.dart';
import 'package:frontend/features/transaction/providers/transaction_provider.dart';
import 'package:frontend/routes/app_routes.dart';
import 'package:get/get.dart';
import 'package:dio/dio.dart';

class OutboundTransactionController extends GetxController with TErrorHandler {
  final TransactionProvider _provider = TransactionProvider();

  final RxList<TransactionDetailModel> cartItems =
      <TransactionDetailModel>[].obs;
  final TextEditingController noteController = TextEditingController();

  final RxString selectedReason = TTexts.reasonRetailSale.obs;
  final RxInt otherFinancialEffect = 0.obs;

  final List<String> predefinedReasons = [
    TTexts.reasonRetailSale,
    TTexts.reasonWholesale,
    TTexts.reasonDamaged,
    TTexts.reasonOther,
  ];

  @override
  void onInit() {
    super.onInit();
    _handleAutoCheckoutArguments();
  }

  // =======================================================
  // 1. AUTO-CHECKOUT LOGIC
  // =======================================================
  void _handleAutoCheckoutArguments() {
    final args = Get.arguments;
    if (args != null &&
        args is Map<String, dynamic> &&
        args.containsKey('autoAddItems')) {
      final items = args['autoAddItems'] as List<dynamic>;

      for (var item in items) {
        final pkg = item['package'] as ProductPackageModel;
        final inv = item['inventory'] as InventoryModel;
        final qty = item['quantity'] as int;

        final cartData = {
          'productPackageId': pkg.productPackageId,
          'displayName': pkg.displayName,
          'packageInfo': pkg,
          'importPrice': pkg.importPrice,
          'sellingPrice': pkg.sellingPrice,
          'currentStock': qty,
          'reorderThreshold': inv.reorderThreshold,
        };

        addToCart(cartData, quantity: qty, customPrice: pkg.sellingPrice);
      }

      selectedReason.value = TTexts.reasonOther;
      noteController.text = TTexts.autoGeneratedClearanceNote.tr;
    }
  }

  // =======================================================
  // 2. VIEW CALLBACKS
  // =======================================================

  int get totalItems => cartItems.length;

  void handleExit() {
    if (cartItems.isEmpty) {
      Get.back();
    } else {
      Get.dialog(
        TCustomDialogWidget(
          title: TTexts.discardTransactionTitle.tr,
          description: TTexts.discardTransactionDesc.tr,
          icon: const Text('⚠️', style: TextStyle(fontSize: 40)),
          primaryButtonText: TTexts.exitAnyway.tr,
          secondaryButtonText: TTexts.cancel.tr,
          onPrimaryPressed: () {
            Get.back();
            Get.back();
          },
          onSecondaryPressed: () => Get.back(),
        ),
      );
    }
  }

  void updateQuantity(int index, int newQuantity) {
    if (index >= 0 && index < cartItems.length) {
      final currentItem = cartItems[index];
      updateCartItem(currentItem.productPackageId ?? '', newQuantity,
          currentItem.unitPrice);
    }
  }

  void handleExportWithPriceCheck() => submitTransaction();

  void selectReason(String reason) => selectedReason.value = reason;

  // =======================================================
  // 3. CART ACTIONS
  // =======================================================
  void addToCart(Map<String, dynamic> data,
      {int quantity = 1, double? customPrice}) {
    final String packageId = data['productPackageId'];
    final existingItemIndex =
        cartItems.indexWhere((item) => item.productPackageId == packageId);

    if (existingItemIndex >= 0) {
      final currentItem = cartItems[existingItemIndex];
      cartItems[existingItemIndex] = TransactionDetailModel(
        productPackageId: currentItem.productPackageId,
        quantity: currentItem.quantity + quantity,
        unitPrice: customPrice ?? currentItem.unitPrice,
        packageInfo: currentItem.packageInfo,
        currentStock: currentItem.currentStock,
        reorderThreshold: currentItem.reorderThreshold,
      );
    } else {
      cartItems.add(TransactionDetailModel(
        productPackageId: packageId,
        quantity: quantity,
        unitPrice: customPrice ?? (data['sellingPrice'] ?? 0.0).toDouble(),
        packageInfo: data['packageInfo'],
        currentStock: data['currentStock'] ?? 0,
        reorderThreshold: data['reorderThreshold'] ?? 0,
      ));
    }
  }

  void updateCartItem(String packageId, int newQuantity, double newPrice) {
    if (newQuantity <= 0) {
      removeCartItem(packageId);
      return;
    }
    final index =
        cartItems.indexWhere((item) => item.productPackageId == packageId);
    if (index >= 0) {
      final currentItem = cartItems[index];
      cartItems[index] = TransactionDetailModel(
        productPackageId: currentItem.productPackageId,
        quantity: newQuantity,
        unitPrice: newPrice,
        packageInfo: currentItem.packageInfo,
        currentStock: currentItem.currentStock,
        reorderThreshold: currentItem.reorderThreshold,
      );
    }
  }

  void removeCartItem(String packageId) {
    cartItems.removeWhere((item) => item.productPackageId == packageId);
  }

  void clearCart() {
    cartItems.clear();
    noteController.clear();
    selectedReason.value = TTexts.reasonRetailSale;
    otherFinancialEffect.value = 0;
  }

  double get totalAmount {
    return cartItems.fold(
        0.0, (sum, item) => sum + (item.quantity * item.unitPrice));
  }

  // =======================================================
  // 4. SUBMIT & FIX NaN ERROR
  // =======================================================
  void submitTransaction() async {
    if (cartItems.isEmpty) {
      TSnackbarsWidget.warning(
          title: TTexts.warningTitle.tr, message: TTexts.emptyCartWarning.tr);
      return;
    }

    final String reasonStr = selectedReason.value.tr;
    final String noteStr = noteController.text.trim();
    final String finalNote = noteStr.isNotEmpty
        ? '[$reasonStr] $noteStr'
        : '[$reasonStr] ${TTexts.outboundTransaction.tr}';

    final mappedItems = cartItems
        .map((item) => {
              'productPackageId': item.productPackageId,
              'quantity': item.quantity.toInt(),
              'unitPrice': item.unitPrice.toDouble(),
            })
        .toList();

    try {
      FullScreenLoaderUtils.openLoadingDialog(
          TTexts.loadingCreatingTransaction.tr);

      // Gọi API tạo hóa đơn xuất kho
      final response = await _provider.createExportTransaction(
        note: finalNote,
        items: mappedItems,
      );

      FullScreenLoaderUtils.stopLoading();

      // Parse kết quả trả về
      final transactionResult = TransactionModel.fromJson(response);

      // Refresh data các màn hình khác
      if (Get.isRegistered<HomeController>()) {
        Get.find<HomeController>().loadAllHomeData();
      }
      if (Get.isRegistered<ReportController>()) {
        Get.find<ReportController>().fetchTransactions();
      }

      clearCart();

      // Chuyển hướng sang trang Summary
      Get.offNamed(AppRoutes.transactionSummary, arguments: transactionResult);
    } on DioException catch (e) {
      FullScreenLoaderUtils.stopLoading();
      // Xử lý lỗi xung đột tồn kho (409 Conflict)
      if (e.response?.statusCode == 409) {
        final List<dynamic> conflicts = e.response?.data['conflicts'] ?? [];
        List<String> conflictedNames = [];

        for (var conflict in conflicts) {
          final String pkgId = conflict['productPackageId'];
          final int newStock = conflict['currentStock'] ?? 0;
          final index =
              cartItems.indexWhere((i) => i.productPackageId == pkgId);

          if (index != -1) {
            final item = cartItems[index];
            final productName =
                item.packageInfo?.displayName ?? TTexts.unknownProduct.tr;
            conflictedNames.add(
                "$productName (${TTexts.actualStock.tr}: $newStock) ➔ ${TTexts.autoRemovedFromCart.tr}");
            cartItems.removeAt(index);
          }
        }
        Get.dialog(TCustomDialogWidget(
          title: TTexts.outOfStockTitle.tr,
          description:
              "${TTexts.outOfStockDesc.tr}\n\n${TTexts.updatedListLabel.tr}\n${conflictedNames.map((e) => "• $e").join("\n")}",
          icon: const Text('🛒', style: TextStyle(fontSize: 40)),
          primaryButtonText: TTexts.confirm.tr,
          onPrimaryPressed: () => Get.back(),
        ));
      } else {
        handleError(e);
      }
    }
  }

  void openScanner() {
    Get.to(() => TBarcodeScannerLayout(
          title: TTexts.scanProductBarcode.tr,
          onScanned: (code) {
            Get.back();
            Get.toNamed(AppRoutes.outboundTransactionItemAdd, arguments: code);
          },
        ));
  }
}
