// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8HcEHC8duxFFzGm0a0uDiDnUTYSlukj8',
    appId: '1:1019570928869:web:09f22fc85eef63668fa80c',
    messagingSenderId: '1019570928869',
    projectId: 'storix-6ac34',
    authDomain: 'storix-6ac34.firebaseapp.com',
    storageBucket: 'storix-6ac34.firebasestorage.app',
    measurementId: 'G-HM10X2CF1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNUABGADg9gJ-8Y39WL5tFW7cLtSmheyk',
    appId: '1:365917199256:android:0b2207bf054e53d2dc29ed',
    messagingSenderId: '365917199256',
    projectId: 'storix-512ff',
    storageBucket: 'storix-512ff.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtFDlS_idospFWJTKGJppmvSpIgrfMcl0',
    appId: '1:365917199256:ios:4c5bbddfd6a9b89fdc29ed',
    messagingSenderId: '365917199256',
    projectId: 'storix-512ff',
    storageBucket: 'storix-512ff.firebasestorage.app',
    iosBundleId: 'com.fourmonkeysstudio.storix',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW1ajrDkzddsnXfzLpPps-TjC6vofm4Mo',
    appId: '1:1019570928869:ios:82179325be2006b68fa80c',
    messagingSenderId: '1019570928869',
    projectId: 'storix-6ac34',
    storageBucket: 'storix-6ac34.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8HcEHC8duxFFzGm0a0uDiDnUTYSlukj8',
    appId: '1:1019570928869:web:83dedfec29a0fac88fa80c',
    messagingSenderId: '1019570928869',
    projectId: 'storix-6ac34',
    authDomain: 'storix-6ac34.firebaseapp.com',
    storageBucket: 'storix-6ac34.firebasestorage.app',
    measurementId: 'G-TH7K9NDJG9',
  );
}
