name: Backup Supabase

on:
  schedule:
    - cron: "0 18 * * 1" # UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    permissions:
      contents: read # tránh ghi đè permission mặc định
      id-token: write # enable OIDC for token rotation

    environment: ${{ vars.ENVIRONMENT }}

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

      AWS_REGION: ap-southeast-1
      BACKUP_BUCKET: ${{ secrets.BACKUP_BUCKET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v2
        with:
          version: 2.111.0

      - name: Link Supabase Project
        run: |
          supabase link \
            --project-ref "$SUPABASE_PROJECT_ID"

      - name: Prepare backup directories
        run: |
          mkdir -p backup
          mkdir -p storage-backup

      - name: Backup PostgreSQL
        run: |
          docker run --rm \
            -e DATABASE_URL="$DATABASE_URL" \
            -v "${{ github.workspace }}/backup:/backup" \
            postgres:17 \
            sh -c '
              pg_dump \
                --schema=public \
                --schema=auth \
                --format=custom \
                --no-owner \
                --no-privileges \
                --file=/backup/backup.dump \
                "$DATABASE_URL"
            '

      - name: Backup Storage
        run: |
          supabase \
            --experimental \
            storage cp \
            -r \
            ss:///images \
            ./storage-backup/images

      - name: Configure AWS Credentials
        if: success()
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ vars.OIDC_AUTHORIZED_ROLE }}

      - name: Upload Database Backup
        run: |
          TODAY=$(date +%F)

          aws s3 cp \
            backup/backup.dump \
            s3://$BACKUP_BUCKET/database/$TODAY.dump

      - name: Upload Storage Backup
        run: |
          TODAY=$(date +%F)

          aws s3 sync \
            storage-backup/images \
            s3://$BACKUP_BUCKET/storage/$TODAY/images

      - name: Cleanup
        if: always()
        run: |
          rm -rf backup
          rm -rf storage-backup
