name: CD workflow for backend (Lambda)

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend

    env:
      AWS_REGION: ap-southeast-1
      AWS_ACCOUNT_ID: 430118860011
      ECR_REPOSITORY: storix-backend
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_LAMBDA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_LAMBDA_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push backend image
        id: build
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          file: ./backend/Dockerfile.lambda
          platforms: linux/arm64
          provenance: false
          sbom: false
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Inspect image
        run: |
          docker inspect \
            "${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          echo "Image ID:"
          echo "${{ steps.build.outputs.imageid }}"
          echo '${{ steps.build.outputs.metadata }}' | jq .

      - name: Compare image
        run: |
          docker history \
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

          docker image ls

          docker image inspect \
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            --format='Size={{.Size}} bytes'
