name: Keep Alive Supabase

on:
  schedule:
    - cron: "0 18 * * 5" # UTC
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    environment: ${{ vars.ENVIRONMENT }}

    steps:
      - name: Ping Supabase
        run: |
          curl -sS \
            -H "apikey: ${{ secrets.SUPABASE_PUBLISHABLE_KEY }}" \
            "${{ secrets.SUPABASE_URL }}/rest/v1/rpc/keep_alive"
